### ISSUE TITLE
How should I access the GObjectIntrospection information from a given module?

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome2/yard-gobject-introspection#1] opened 2016-12-02 14:08 UTC
@kou,

I started the yard plugin with this : 

```ruby
require "yard"
require "gobject-introspection"

class GObjectIntropsectionHandler < YARD::Handlers::Ruby::Base
  handles :module

  def process
    base = File.join(File.dirname(File.expand_path(statement.file)))
    $LOAD_PATH.unshift(base)

    puts "-- Load module info"

    require File.expand_path(statement.file)

    module_name = statement[0].source
    puts module_name
    current_module = Object.const_get("#{module_name}")
    current_module.init if current_module.respond_to?(:init)

    current_module.constants.each do |c|
      puts "#{c} #{current_module.const_get(c).class}"
    end
  end
end
```

Then I build and install the gem like this:

```
gem build yard-gobject-introspection.gemspec
gem install --local --user-install yard-gobject-introspection-0.0.1.pre.gem
```

and use it with (I disable the doc generation for now because those are only test):

```
yard --plugin yard-gobject-introspection doc --no-output --no-save gnumeric/lib/gnm.rb
```

The output show me that I am able to list all the elements (constants, classes, modules) that exists in the module.

After that I will have to register them as new [ `YARD::CodeObjects`](http://www.rubydoc.info/gems/yard/file/docs/Handlers.md#Creating_a_new_Code_Object) but as there is no written code to provide, I will have to : 

1.  get the information of those objects
2.  use those information in order to configure the instance of the `ClassObject` for example.

I would like that we focus on the first point. How should I get such information? 

a.  should I use the **.gir** file and make xml requests on it.
b.  should I use the gobject-instropection Loader of the module 

The solution "b" seems great because we could maybe use the renaming functions that are specifics to each module. The problem is that I don't see how to access the loader used in each module.

The solution "a" need that we had some code in order to follow some renaming convention, the positive point is that we will be able to access the `<doc>` element that could be interesting for the documentation. After some researches, it seems that those information can not be obtained via the gobject-introspection lib.

**Comment by kou** [comment] 2016-12-02 14:53
> a. should I use the .gir file and make xml requests on it.

We need to choose "a" because `.typelib` that is loaded by `GObjectIntrospection::Loader` doesn't have document information as you researched.

BTW: You can try your code by the following command line:

```text
% yard doc --load lib/yard-gobject-introspection.rb --no-output --no-save ../ruby-gnome2/gnumeric/lib/gnm.rb
```

**Comment by cedlemo** [comment] 2016-12-02 15:02
> BTW: You can try your code by the following command line:

:) thanks that is really helpfull.

Have you a preference for the xml gem to use ?

**Comment by kou** [comment] 2016-12-04 12:44
> Have you a preference for the xml gem to use ?

I like REXML because it's a standard library. (No additional dependency.)
If you aren't familiar with REXML, I can help you.

**Comment by cedlemo** [comment] 2016-12-04 17:03
> I like REXML because it's a standard library.

Ok

> If you aren't familiar with REXML, I can help you.

Yes I am sure that you can , I saw that you worked on it :-) . 

I will start with the tutorial here: http://www.germane-software.com/software/rexml/docs/tutorial.html. Maybe you know a better source.

**Comment by cedlemo** [comment] 2016-12-05 17:57
@kou,

So I have a realy the basic [gir file loader](https://github.com/ruby-gnome2/yard-gobject-introspection/blob/master/lib/yard-gobject-introspection.rb). Have you any advices or good practices about REXML usage?

**Comment by kou** [comment] 2016-12-06 13:26
I confirmed it. It looks good! I just fixed one point. I removed top-level include.

**Closed as completed** 2016-12-10 10:50 UTC
